### ISSUE TITLE
Scalac Warning

### ISSUE THREAD

**Issue by bennythomps** [schemasafe/troy#141]
For some reason I continue to get the following warning (for all of my schema objects):
```scala
Warning:scalac: {
  import _root_.troy.driver.InternalDsl._;
  import _root_.troy.driver.codecs.PrimitivesCodecs._;
  val prepared = implicitly[com.datastax.driver.core.Session].prepare("\n        INSERT INTO mydb.api_keys (api_key, name, active)\n        VALUES (?, ?, ?)\n        ");
  ((apiKey: com.me.data.models.ApiKey) => {
    <empty>;
    bind(prepared, param(apiKey.apiKey).as[CDT.Uuid], param(apiKey.name).as[CDT.Text], param(apiKey.active).as[CDT.Boolean]).executeAsync(ApiKeyRecord.this.session, scala.concurrent.ExecutionContext.Implicits.global)
  })
}
```
Is this a known issue or is there a common reason for this?

**Comment by tabdulradi** [comment]
It is a [logging statement]([https://github.com/schemasafe/troy/blob/master/troy-macro/src/main/scala/troy/macros/package.scala#L94]) that we forgot to remove before releasing.

**Comment by tabdulradi** [comment]
Logging has been removed in [v0.5](https://github.com/schemasafe/troy/tree/v0.5). Please feel free to reopen the issue if the bug persists.
